# General options
# Accepted log levels: "panic", "fatal", "error", "warn", "info", "debug", "trace"
log_level: "debug"
# Server configuration
server:
  address: "localhost:9999"
  tls:
    cert_path: "./cert/c13n.pem"
    key_path:  "./cert/c13n.key"
  user: example
  # bcrypt hash of RPC password
  pwdhash: replaceme
  graceful_shutdown_timeout: 10
# LN service configuration
lnd:
  address: "localhost:10009"
  tls_path: "~/.lnd/tls.cert"
  macaroon_path: "~/.lnd/data/chain/bitcoin/regtest/admin.macaroon"
  macaroon_timeout_secs: 0
  macaroon_ip: ""
# Application configuration
app:
  default_fee_limit_msat: 3000
# Database configuration
database:
  db_path: "./test.db"
  # Master DB encryption key of fixed length (16, 24, 32 bytes)
  key_path: replaceme
