name: Generate RTD documentation

on:
  push:
    branches:
      - develop

jobs:
  build-rtd-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish latest service image
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: c13n-api-rtd-generator
          docker-image-tag: latest
          dockerfile-path: ./docker/readthedocs/Dockerfile
          build-context: ./

      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/c13n-io/c13n-api-rtd-generator:latest
          options: -v ${{ github.workspace }}:/c13n
          run: |
            echo "Running Script"
            /build_rtd.sh

      - name: Push to rtd repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs/c13n-api-docs'
          destination-github-username: 'c13n-io'
          destination-repository-name: 'c13n-api-docs'
          user-email: c13n-api-docs-deployment@c13n.io
          target-branch: master
